---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./paperless/ks.yaml
  #  - monica
  # - ./affine/ks.yaml
  - ./atuin/ks.yaml
  - ./actual/ks.yaml
  - ./lubelog/ks.yaml
  - ./mealie/ks.yaml
  #  - ./wallabag/ks.yaml
  #  - ./linkwarden/ks.yaml
  #  - ./linkding/ks.yaml
  - ./stirling-pdf/ks.yaml
  # - ./radicale/ks.yaml
  - ./karakeep/ks.yaml
  - ./it-tools/ks.yaml
  - ./affine/ks.yaml
  # - ./outline/ks.yaml
