---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs-system
resources:
  - ./namespace.yaml
  - ./ks.yaml
