apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./thanos/ks.yaml
  - speedtest-exporter
  - ./kubernetes-dashboard/ks.yaml
  - ./goldilocks/ks.yaml
  - ./vpa/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./node-exporter/ks.yaml
  - ./vector/ks.yaml
  - ./loki/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./gatus/ks.yaml
