apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - bjw-s-labs.yaml
  - deliveryhero-charts.yaml
  - external-dns-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - jetstack-charts.yaml
  - k8s-gateway.yaml
  - metallb.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - minio-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - weave-gitops.yaml
  - longhorn-charts.yaml
  - mojo2600-charts.yaml
  - emqx-charts.yaml
  - influxdata-charts.yaml
  - nextcloud-charts.yaml
  - hashicorp-charts.yaml
  - coredns.yaml
  - piped.yaml
  - intel.yaml
  - jameswynn.yaml
  - angelnu.yaml
  - indeed-eng.yaml
  - authentik-charts.yaml
  - harbor-charts.yaml
  - ingress-nginx-charts.yaml
  - kubernetes-dashboard-charts.yaml
