apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mosquitto/ks.yaml
  - ./home-assistant/ks.yaml
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./wyze-bridge/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./n8n/ks.yaml
  - ./trmnl/ks.yaml
