apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minio/ks.yaml
  - ./homepage/ks.yaml
  - ./miniflux/ks.yaml
  - ./ghost/ks.yaml
  - ./ghostfolio/ks.yaml
  - ./glance/ks.yaml
  - ./headlamp/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./divedb/ks.yaml
  - ./headlamp/ks.yaml
