apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - networking
  - system-upgrade
  - media
  - monitoring
  - data
  - home
  - productivity
  - ./cert-manager/ks.yaml
  - security
  - system
  - ./coder/ks.yaml
  - ./actions-runner-system/namespace.yaml
  - ./actions-runner-system/actions-runner-controller/ks.yaml
  # - vault
