apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc
  - jellyfin
  - ./plex/ks.yaml
  - qbittorrent
  - ./bazarr/ks.yaml
  - ./lidarr/ks.yaml
  - ./immich/ks.yaml
  - ./overseerr/ks.yaml
  - radarr
  - readarr
  - ./sabnzbd/ks.yaml
  - sonarr
  - ./tautulli/ks.yaml
  - photoprism
  # - tdarr
  - nextcloud
  - ./piped/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
