apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc
  - ./jellyfin/ks.yaml
  - ./plex/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./bazarr/ks.yaml
  - ./immich/ks.yaml
  - ./overseerr/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./nextcloud/ks.yaml
  - ./piped/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./pinchflat/ks.yaml
  - ./calibre/ks.yaml
  - ./slskd/ks.yaml
  - ./soulsync/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./tvheadend/ks.yaml
